<?php

namespace ISL\CrearchitexBundle\Repository;

/**
 * equipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipeRepository extends \Doctrine\ORM\EntityRepository
{
}
